### ISSUE TITLE
Release numbers

### ISSUE THREAD

**Issue by pdesmarets** [Qwin/Joi#3]
Hi Robert.  Not sure you saw my email.  Thanks for merging my pull request.  But there are a couple of issues in order to make the release available for download from within the application:
1) the package.json file needs to be update with a bump for the version number
2) we use semver semantic numbering, so you can only have 3 segments for the tag (version number) instead of the 4 segment you used in the tags.

Can you please bump both to 0.1.1 and the upgrade should then show in the DB Target Plugin Manager?  Thx!

**Comment by Qwin** [comment]
I updated the versioning. Thanks for letting me know.

**Comment by pdesmarets** [comment]
Yes.  Worked for me!  Thx!

**Comment by pdesmarets** [comment]
Closed.
